services:
  bourso2ynab:
    image: bourso2ynab
    container_name: bourso2ynab
    ports:
      - "1000:5000"
    env_file: .env
    environment:
      - DB_FILEPATH=db.json
    volumes:
      - ./db.json:/bourso2ynab/db.json
      - ./secrets.json:/bourso2ynab/secrets.json
