version: "3.9"
services:
  bourso2ynab:
    image: bourso2ynab
    container_name: bourso2ynab
    ports:
      - "1000:5000"
    env_file: .env
    environment:
      - DB_FILEPATH=db.json
    volumes:
      - ./db.json:/python-docker/db.json
