[project]
name = "bourso2actual"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "actualpy>=0.7.0",
    "flask>=3.1.0",
    "ipdb>=0.13.13",
    "ipython>=8.29.0",
    "loguru>=0.7.2",
    "pandas>=2.2.3",
    "pysondb-v2>=2.2.0",
    "pytest-env>=1.1.5",
    "pytest-mock>=3.14.0",
    "pytest>=8.3.3",
    "python-dotenv>=1.0.1",
    "ruff>=0.8.1",
    "selenium>=4.26.1",
    "ynab-api",
    "gunicorn>=23.0.0",
    "tenacity>=9.0.0",
]

[tool.uv.sources]
ynab-api = { git = "https://github.com/dmlerner/ynab-api.git", rev = "nullfix" }
